name: source_maps2
version: 0.10.11-dev

description: Library to programmatically manipulate source map files.
homepage: https://github.com/dart-lang/source_maps

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  source_span: ^1.8.0

dev_dependencies:
  extra_pedantic: ^2.0.0
  test: ^1.16.0
